
---
title: "Descriptive Statistics"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()


colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


```{r}
#start with clean workspace 
rm(list=ls())
getwd()
```

```{r}
modelki2 <- lm(ki ~ gender + dutch + pub_first, data=datadef_df)
summary(modelki2)
```

```{r}
results <- as.data.frame(summary(modelki2)$coefficients)
```

```{r}
#install.packages("kableExtra")
library(kableExtra)
```
```{r}
exp(-2)
```

