---
title: "Scraping Twitter"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r warning=FALSE, globalsettings, echo=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Twitter 
Here I scrape Twitter Data for both the data science and the sociology department. 

```{r, eval=FALSE}
#install.packages("httr")
#install.packages("jsonlite")
require(httr)
require(jsonlite)
require(dplyr)
bearer_token <- Sys.getenv("AAAAAAAAAAAAAAAAAAAAAKrlhQEAAAAA2FanC26ruzLTXpxNhyzmoiW67dc%3DbKf1jIQ1ocJS3TJQcJDAihczebimKPGjrqsOZSEXAoiGUnK83x")
headers <- c(`Authorization` = sprintf('Bearer %s', bearer_token))
auth_setup_default()
```


```{r, eval=FALSE}
library ("rtweet")
```

```{r, eval=FALSE}
data_twitter1 <- list()

for (i in 1:nrow(data_df)) { 
  
  time <- runif (1,0,3)
  Sys.sleep(time)
  print(i)
  
  data_twitter1[[i]] <- search_users(data_df[i, c("name")], n=1, parse=FALSE, token=NULL, verbose=TRUE)
  } 

data_twittercopy <- data_twitter1
data_twitter1[[14]][[1]]

length(data_twitter1[[1]][[1]])

twid <- NA
twname <-NA
twscreenname <- NA
twfollowercount <- NA

for (i in 1:length(data_twitter1)) {
  if (!length(data_twitter1[[i]][[1]])==0) {
  twid[i] <- data_twitter1[[i]][[1]]$id[1] 
  twname[i] <- data_twitter1[[i]][[1]]$name[1]
  twscreenname[i] <-data_twitter1[[i]][[1]]$screen_name[1]
  twfollowercount[i] <- data_twitter1[[i]][[1]]$followers_count[1]
  }
}

data_twitterinfo <- as.data.frame(cbind(twid, twname, twscreenname, twfollowercount))

data_df <- cbind(data_df, data_twitterinfo)


data_twitter1[[1]][[1]]$id
str(data_twitter1)

save(data_twitter1, file="./data/data_twitter.RData")
save(data_df, file = "addfiles\\data_df.RData") 


```

```{r, echo=FALSE}
load("/Users/anuschka/Documents/labjournal/data/data_twitter.RData")
```

```{r}
head(data_twitter1)
```

# Sociology 

```{r, eval=FALSE}
#Now I would like to do the same for the sociology department. Ronald Batenburg's result is not right (I don't think he has Twitter, the first results is a radical right person), but for the others I randomly checked they seemed ok. 

soc_twitter <- list()

for (i in 1:nrow(soc_df)) { 
  
  time <- runif (1,0,3)
  Sys.sleep(time)
  print(i)
  
  soc_twitter[[i]] <- search_users(soc_df[i, c("name")], n=1, parse=FALSE, token=NULL, verbose=TRUE)
  } 


save(soc_twitter, file="./data/soc_twitter.RData")

twids <- NA
twnames <-NA
twscreennames <- NA
twfollowercounts <- NA

for (i in 1:length(soc_twitter)) {
  if (!length(soc_twitter[[i]][[1]])==0) {
  twids[i] <- soc_twitter[[i]][[1]]$id[1] 
  twnames[i] <- soc_twitter[[i]][[1]]$name[1]
  twscreennames[i] <-soc_twitter[[i]][[1]]$screen_name[1]
  twfollowercounts[i] <- soc_twitter[[i]][[1]]$followers_count[1]
  }
}

soc_twitterinfo <- as.data.frame(cbind(twids, twnames, twscreennames, twfollowercounts))

soc_df <- cbind(soc_df, soc_twitterinfo)

names(soc_twitterinfo)[names(soc_twitterinfo) == 'twnames'] <- 'name'


soc_df<- merge(soc_df, soc_twitterinfo, all = TRUE, by = "name")
head(cv_tot_panel)

soc_dfc <- soc_df

soc_df <- soc_df[-c (33:40), , drop=FALSE]
save(soc_df, file="./data/soc_df.RData")
```

```{r, echo=FALSE}
load("/Users/anuschka/Documents/labjournal/data/soc_twitter.RData")
```

```{r}
head(soc_twitter)
```


```{r, eval=FALSE}
#If I ever get the loop fixed, the Kardashian Index can be calculated using the following code. Of course I have to adapt this to the names of my own variables. 
calculate_kardashian_index <- function(twitter_followers, total_citations) {
  
  # Set F_a as number of twitter followers:
  F_a <- twitter_followers
  
  # Calculate F_c using equation 1 of Hall (2014):
  F_c <- 43 * (total_citations ^ 0.32)
  
  # Retrurn Kardashian Index (equation 2 of Hall 2014):
  F_a / F_c
}
```


