---
title: "Scraping Twitter"
author: "Anuschka Peelen"
date: "`r Sys.Date()`"
output: html_document
---

```{r warning=FALSE, globalsettings, echo=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Request correlation 
load("/Users/anuschka/Downloads/pubnets/datatwitterinfo_df.RData")
```


```{r}
cor.test(as.numeric(datadef_df$total_cites), as.numeric(data_twitterinfo$ki))
cor.test(as.numeric(datadef_df$total_cites), as.numeric(data_twitterinfo$twfollowercount))

plot(as.numeric(datadef_df$total_cites), as.numeric(data_twitterinfo$ki))


```

```{r}
#We see in the plot that there are outliers. Let's control (also in the model) for having twitter or not. I will assume that all the individuals that have an NA or 0/1 followers, don't have twitter. 

data_twitterinfo$twfollowercount <- as.numeric(data_twitterinfo$twfollowercount)

datadef_df$twitter_dum <- -1
datadef_df$twitter_dum[data_twitterinfo$twfollowercount==0 | data_twitterinfo$twfollowercount==1] <- 0
datadef_df$twitter_dum[data_twitterinfo$twfollowercount > 1] <- 1
datadef_df$twitter_dum[is.na(data_twitterinfo$twfollowercount)] <- 0

table(datadef_df$twitter_dum, useNA = "always")

class(data_twitterinfo$twfollowercount)



```

```{r}
sel <- datadef_df$twitter_dum==1
cor.test(as.numeric(datadef_df$total_cites[sel]), as.numeric(data_twitterinfo$twfollowercount[sel]))

plot(as.numeric(datadef_df$total_cites[sel]), as.numeric(data_twitterinfo$ki[sel]))
```

```{r}
soc_twitterinfo$twfollowercount <- as.numeric(soc_twitterinfo$twfollowercount)

socdef_df$twitter_dum <- -1
socdef_df$twitter_dum[soc_twitterinfo$twfollowercount==0 | soc_twitterinfo$twfollowercount==1] <- 0
socdef_df$twitter_dum[soc_twitterinfo$twfollowercount > 1] <- 1
socdef_df$twitter_dum[is.na(soc_twitterinfo$twfollowercount)] <- 0

table(socdef_df$twitter_dum, useNA = "always")
```

```{r, eval=FALSE}
save(socdef_df, file="/Users/anuschka/Documents/labjournal/data/socdef_df.RData")
```



```{r, eval=FALSE}
#Dit moet eigenlijk verplaatst worden naar het webscrape-gedeelte. 
load("/Users/anuschka/Downloads/pubnets/data/data_df_publications.RData")

names(data_twitterinfo)[5] <- "gs_id"

for (i in c("TKvd_Z4AAAAJ", "Apxg6tgAAAAJ")) {
    # drop google scholar ids that look suspiciously productive
    datadef_df <- datadef_df[!datadef_df$gs_id == i, ]
    data_df_publications <- data_df_publications[!(data_df_publications$gs_id == i), ]
    data_twitterinfo <- data_twitterinfo[!(data_twitterinfo$gs_id == i), ]
} 
```

```{r}
save(datadef_df, file="/Users/anuschka/Documents/labjournal/data/datadef_df.RData")
save(data_df_publications, file="/Users/anuschka/Documents/labjournal/data/data_df_publications.RData")
save(data_twitterinfo, file="/Users/anuschka/Documents/labjournal/data/data_twitterinfo.RData")
```


```{r}
#library(stringr)
#library(tidyverse)
#empty adjacency matrix for the years 2001-2010
dnetwork2016_2017 <- matrix(NA, nrow=nrow(datadef_df), ncol=nrow(datadef_df))
dnetwork2018_2019 <- matrix(NA, nrow=nrow(datadef_df), ncol=nrow(datadef_df))
dnetwork2020_2022 <- matrix(NA, nrow=nrow(datadef_df), ncol=nrow(datadef_df))

#select publications of the corresponding time era
pubs_sel <- data_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2016 & year<=2017)
#fill the matrix
for (ego in 1: nrow(datadef_df)) {
  name_ego <- datadef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(datadef_df)){
    name_alter <- datadef_df$last_name[alter] #which alter? 
    dnetwork2016_2017[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1)  #did alter publish with ego
  }
}
#select publications of the corresponding time era
pubs_sel <- data_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2018 & year<=2019)
#fill the matrix
for (ego in 1: nrow(datadef_df)) {
  name_ego <- datadef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(datadef_df)){
    name_alter <- datadef_df$last_name[alter] #which alter? 
    dnetwork2018_2019[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1) #did alter publish with ego
  }
}
#select publications of the corresponding time era
pubs_sel <- data_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2020 & year<=2022)
#fill the matrix
for (ego in 1: nrow(datadef_df)) {
  name_ego <- datadef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(datadef_df)){
    name_alter <- datadef_df$last_name[alter] #which alter? 
    dnetwork2020_2022[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1) #did alter publish with ego
  }
}
c(dim(dnetwork2016_2017),3)
dnet_array <- array(data = c(dnetwork2016_2017, dnetwork2018_2019, dnetwork2020_2022), dim=c(dim(dnetwork2016_2017),3))
dnet_array[1,1,1]
```


```{r}
save(dnet_array, file="/Users/anuschka/Documents/labjournal/data/data_net_array.RData")
```

```{r}
for (i in c("_ukytQYAAAAJ", "lkVq32sAAAAJ", "p3IwtT4AAAAJ")) {
    # drop google scholar ids that look suspiciously productive
    socdef_df <- socdef_df[!socdef_df$gs_id == i, ]
    soc_df_publications <- soc_df_publications[!(soc_df_publications$gs_id == i), ]
    soc_staff_cit <- soc_staff_cit[!(soc_staff_cit$gs_id == i), ]
  
} 
```


```{r}
library(stringr)
library(tidyverse)
#empty adjacency matrix for the years 2001-2010
network2016_2017 <- matrix(NA, nrow=nrow(socdef_df), ncol=nrow(socdef_df))
network2018_2019 <- matrix(NA, nrow=nrow(socdef_df), ncol=nrow(socdef_df))
network2020_2022 <- matrix(NA, nrow=nrow(socdef_df), ncol=nrow(socdef_df))

load("/Users/anuschka/documents/labjournal/data/soc_df_publications.RData")

#select publications of the corresponding time era
pubs_sel <- soc_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2016 & year<=2017)
#fill the matrix
for (ego in 1: nrow(socdef_df)) {
  name_ego <- socdef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(socdef_df)){
    name_alter <- socdef_df$last_name[alter] #which alter? 
    network2016_2017[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1)  #did alter publish with ego
  }
}
#select publications of the corresponding time era
pubs_sel <- soc_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2018 & year<=2019)
#fill the matrix
for (ego in 1: nrow(socdef_df)) {
  name_ego <- socdef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(socdef_df)){
    name_alter <- socdef_df$last_name[alter] #which alter? 
    network2018_2019[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1) #did alter publish with ego
  }
}
#select publications of the corresponding time era
pubs_sel <- soc_df_publications %>%
              mutate(author = tolower(author)) %>%
              filter(year>=2020 & year<=2022)
#fill the matrix
for (ego in 1: nrow(socdef_df)) {
  name_ego <- socdef_df$last_name[ego] #which ego? 
  pubs_sel2 <- pubs_sel[str_detect(pubs_sel$author, name_ego),] #publications of ego
  for (alter in 1:nrow(socdef_df)){
    name_alter <- socdef_df$last_name[alter] #which alter? 
    network2020_2022[ego,alter] <- as.numeric(sum(str_detect(pubs_sel2$author, name_alter)) > 1) #did alter publish with ego
  }
}
c(dim(network2016_2017),3)
soc_net_array <- array(data = c(network2016_2017, network2018_2019, network2020_2022), dim=c(dim(network2016_2017),3))

```



```{r}
save(soc_net_array, file="/Users/anuschka/Documents/labjournal/data/socdef_net_array.RData")
```





